server:
  port: 9901
spring:
  application:
    name: order
  datasource:
    username: root
    password: 960213
    url: jdbc:mysql://localhost:3306/springcloud_ordersys?serverTimezone=Asia/Shanghai&useSSL=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka/
  instance:
    instance-id: order-9901
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.zcy.entity